### PR TITLE
Adding new attibutes of jobs entity appended on API version 1.4

### PR DESCRIPTION
**Pull request by douglasgabriel**
This PR is able to:
- Add new attributes to jobs resource appended on LXCA API version 1.4

### CODE REVIEW

**Comment by douglasgabriel** [comment]
@walteraa

**Comment by walteraa** [comment]
It looks good to merge, but I don't know if there's any guideline about testing params in this client. I mean, you are testing both new properties in the same test. @AndreyMenezes @rodneyhbrown7 is it ok for you guys?

**Comment by Sanmoo** [comment]
@AndreyMenezes has left the company so I'm not sure he will continue to review PRs.
@CharlleDaniel and @rodneyhbrown7 please address @walteraa concerns so that we can merge this and all other related pull requests.

**Comment by Sanmoo** [comment]
@walteraa would you mind elaborating a bit more about which contexts you are suggesting us to add, what do you mean by behavioral tests and structural checks, possibly with examples?

About future changes, our idea is to refactor the client to support multiple LXCA versions. This way we would not have to deal with API changes breaking tests since it would be coupled to it's version.

**Comment by walteraa** [comment]
@Sanmoo sure!

Isn't a good idea contextualizing tests with versions as it is now, a good "meaning" for context could be a group of tests which are missing some group of attributes, for example.

Structural tests are interesting to ensure that a specific property is always a hash, for example. It would be very very interesting to identify some data changing occurs in the API, as happened before(we had some errors in the ManageIQ Provider regarding an API change).

The last one ensures that when something is really missing, the test should catch this issue. Once the blueprint API always is returning a "correct" data structure, we are always getting false-positive. 

I heard about supporting multiple versions but is important keep using some good practices of testing that could help us to track issues in the future.

**Pull request merged**
