### PR TITLE
[WIP] Adding support to version 2.0 attributes

### PR DESCRIPTION
**Pull request by douglasgabriel**
This PR is able to:
- adds the new API attributes inserted on the version 2.0;
- Add specs for test the parse of the new attributes.

### CODE REVIEW

**Comment by walteraa** [comment]
This PR should be splitted in many others. You are changing 17 files into 2 commits, all files aren't related.

**Comment by CharlleDaniel** [comment]
@walteraa  I think that he can use this PR for something, please wait for @douglasgabriel.

**Comment by walteraa** [comment]
ok @CharlleDaniel then is necessary change the title and the description of the PR. :smile:

**Comment by douglasgabriel** [comment]
PR splitted:
https://github.com/lenovo/xclarity_client/pull/80
https://github.com/lenovo/xclarity_client/pull/79
https://github.com/lenovo/xclarity_client/pull/78

**Pull request closed without merging**
