### PR TITLE
Changed and cleaned the events, cmm and fan entities to support LXCA …

### PR DESCRIPTION
**Pull request by CharlleDaniel**
This PR is able to:
- Modify attributes of events, cmm and fan entities and blueprints to support the LXCA API 1.3

### CODE REVIEW

**Comment by CharlleDaniel** [comment]
@walteraa

**Comment by walteraa** [comment]
LGTM

**Comment by CharlleDaniel** [comment]
@walteraa I checked all keys in all elements returned for the API 1.3

**Comment by AndreyMenezes** [comment]
LGTM

**Pull request merged**
