### PR TITLE
Add support for the remote control endpoint

### PR DESCRIPTION
**Pull request by Sanmoo**

### CODE REVIEW

**Comment by Sanmoo** [comment]
@rodneyhbrown7 @CharlleDaniel @douglasgabriel @felipedf @igorrran  please provide feedback when possible

**Comment by rodneyhbrown7** [comment]
The spec test here looks like it will make the call to an actual LXCA instance.  Can you mock the response in the directory docs/apib to satisfy the spec test?

**Comment by Sanmoo** [comment]
@rodneyhbrown7 , thanks for the feedback.
Actually the spec will not try to make actual requests. In facto, WebMock will step in and throw a runtime error if the spec tries to make a real request.
I've already mocked the response for different scenarios in the spec (in the before hooks). I need different scenarios since this particular API will respond with different content structure depending on the kind of server:
For thinkservers and system x servers, it will respond with a downloadable jnlp file. For thinksystems, it will respond with a json with an 'url' field inside. This field will hold a url that can be accessed in the browser to access the remote console.

**Comment by rodneyhbrown7** [comment]
Thanks Sanmoo.  I will merge this.

**Pull request merged**
