### PR TITLE
version bump for recent faraday update

### PR DESCRIPTION
**Pull request by d-m-u**
I don't have permissions to push to this gem, so this is as good as it's going to get. 

Thanks!

### CODE REVIEW

**Comment by d-m-u** [comment]
hey @felipedf could you cut the new branch for this so rubygems can get updated, please?

**Comment by d-m-u** [comment]
@felipedf ping?

**Comment by kbrock** [comment]
Thanks so much @felipedf for merging this.

Do you have a release cycle so my team can plan for when this is is part of your gem?

**Comment by felipedf** [comment]
@d-m-u @kbrock sorry for the delayed response, I was trying to provide the minimum support you guys need here, but unfortunately this repo is left unsupported, I don't have permissions to push this gem to rubygems, and most of the authors are probably unavailable at this point, I suppose @juliancheal has the permission for this if he is available.

**Comment by kbrock** [comment]
@juliancheal @juliancheal @juliancheal (it worked for beetle juice. maybe it works across the pond) in Bath too?)

<3 Hope

**Comment by juliancheal** [comment]
Hey @kbrock it does work! I added @Fryguy to the Rubygem. We're looking into how to move it over to ManageIQ. Ping me if you need anything :)

Beatlejuice out 🎤

**Comment by felipedf** [comment]
Happy it worked out! :rocket:

**Pull request merged**
