### PR TITLE
Change/Clean the attributes of chassis and blueprints to support th…

### PR DESCRIPTION
**Pull request by CharlleDaniel**
This PR is able to:
- Modify attributes of chassis entity and blueprints to support the LXCA API 1.3

Were removed the attributes:
_id
cmmSlots
encapsulation
parent
properties

### CODE REVIEW

**Comment by CharlleDaniel** [comment]
@walteraa

**Comment by CharlleDaniel** [comment]
@skovic, can you review this PR??  :smile:

**Comment by walteraa** [comment]
LGTM

**Comment by CharlleDaniel** [comment]
@walteraa I checked all keys in all elements returned for the API 1.3

**Pull request merged**
