### PR TITLE
Getting appliance data from the /aicc endpoint

### PR DESCRIPTION
**Pull request by douglasgabriel**
This PR is able to:

- Retrieve data about some appliance from the /aicc endpoint:
  - status;
  - name;
  - uuid;
  - build;
  - date;
  - runlevel;
  - version.

### CODE REVIEW

**Comment by douglasgabriel** [comment]
@AndreyMenezes @rodneyhbrown7

**Comment by walteraa** [comment]
You are retrieving more properties than described in the PR description. Is it correct?

**Comment by walteraa** [comment]
@douglasgabriel You shouldn't use Lenovo's Product Backlog references in the PR title(e. g.: XCS-359). Could you edit the PR title, please?

**Comment by douglasgabriel** [comment]
@walteraa for now i'm just getting the attributes of appliance, witch are the describeds on PR description. See the [aicc.rb](https://github.com/lenovo/xclarity_client/pull/66/files#diff-b8d3106fe2298c9672c04e6cbd617972) file

**Comment by walteraa** [comment]
Ok @douglasgabriel Looks good.

**Comment by walteraa** [comment]
Waiting for @AndreyMenezes approval to merge it.

**Pull request merged**
