### PR TITLE
Moving endpoints classes into endpoints folder

### PR DESCRIPTION
**Pull request by douglasgabriel**
**This PR is able to:**
- Move all classes that represents an Xclarity Endpoint into the `endpoints` new folder;
- Create the `XClarityClient::Endpoints` module to centralize all endpoints requirements;
- Remove the endpoints classes requirements from `xclarity_client.rb`.

**Goal**
The main goal of this approach is to improve the code organization and promote a more cohesive structure

### CODE REVIEW

**Comment by rodneyhbrown7** [comment]
Can you describe what you mean by endpoint in this context?  I would expect an endpoint to be a server, chassis, fan, powersupply etc.   

An alternate re-organization would actually have the following folders:
1.  endpoints  -  chassis, server, fan , powersupply, config_pattern, config_profile etc.
2.  services  - discovery, management, ffdc, aaic, persisted_result, user etc.

**Comment by douglasgabriel** [comment]
Yes, endpoints are all the API resources, as you mention as example: chassis, fan, powersupply etc.

Yes, my goal is to split in `endpoints` and `services` like I do in this another PR: https://github.com/lenovo/xclarity_client/pull/91

**Comment by douglasgabriel** [comment]
Oh, I think that I got your question better...

So, in this context the `endpoints` folder is where all the `DTOs` that represents all the LXCA API `resources`, mapped in this `client`, will live.

> With `resources` I mean all the `/<resources>` that the LXCA API provides, it being a really entity or even just a service.

And in #91 the `services` folder should be where all the classes that provides some business logic over this `DTOs` (ex: fetch_all(), query(), change_power_state() etc) will live.

I was able to answer your question, @rodneyhbrown7 ? What do you think?

**Comment by rodneyhbrown7** [comment]
Yes. This makes sense now especially with PR 91.  I approve this.  I will review the set again and start merges later today.

**Pull request merged**
