### PR TITLE
Change version number to 0.5.7

### PR DESCRIPTION
**Pull request by ManasaRaoK**
Change the version number to 0.5.7 to push a new version of this gem onto rubygems.org

### CODE REVIEW

**Comment by walteraa** [comment]
LGTM

**Comment by walteraa** [comment]
@rodneyhbrown7 @AndreyMenezes Always you guys change the client version, is interesting generate a release. The last one was generated by me, is important tag the versions, add release notes, etc.

https://github.com/lenovo/xclarity_client/releases

**Comment by AndreyMenezes** [comment]
@walteraa I believe Rubygems maintain the version of client, We will create new releases for new versions of LXCA. We are testing the 1.3 LXCA version, when everything is ok I will generate new release.

**Comment by walteraa** [comment]
@AndreyMenezes is not recommended depending on external tools such as Rubygems to maintain version. It should be managed here because if a change was needed from Rubygems to another tool, we will "lost" all versions.

**Comment by AndreyMenezes** [comment]
Ok, but we need to have a pattern to generate this releases.

**Comment by walteraa** [comment]
Agreed @AndreyMenezes

**Comment by walteraa** [comment]
@ManasaRaoK I'll merge it after commit message fix.

**Pull request merged**
