### PR TITLE
Updated code as per new code structure and updated schema validation method

### PR DESCRIPTION
**Pull request by umrikar**

### CODE REVIEW

**Comment by rodneyhbrown7** [comment]
Can you squash all of these commits into a single commit and resubmit this pull request?

**Comment by umrikar** [comment]
squashed all changes in single commit

**Comment by felipedf** [comment]
Hi @umrikar looks like you still have 35 commits here,

Instead squashing you can try to reset to your first commit and then amend all your changes to that ( this take less steps )

```bash
# This will join all the commit in the first one.
  git reset 461c293 # this is the id of your first commit
  git status # you can see the files that you changed
  git add .
  git commit --amend
     ctrl + o
     ctrl + x
  git push -f <your remote> <your branch>
```

**Comment by umrikar** [comment]
@felipedf  sure i will do that thanks

**Pull request merged**
